### ISSUE TITLE
homeAction 使用到列表翻页的时候，不适合重复调用homeAction

### ISSUE THREAD

**Issue by ETmanwenhan** [JianweiWangs/RxSwiftMVVM#4]
大神考虑到列表翻页的功能吗？homeAction在翻页的时候无法进行复用哦。重复调用HomeAction会直接崩溃。

**Comment by JianweiWangs** [comment]
先解决问题，Action是可复用的，Action是可以指定入参类型的，这个入参也就是excute时传入的，可以在vc维护page，也可以在vm，而Action的正常的使用是不建议直接拿extcute的返回值的，而是对其进行信号包装的拆分，如果使用过RAC，那么就会很熟悉，因为其等同于Command。
我这个仅仅是个样例demo，简单写了下流程，旨在给一个想使用RxSwift+MVVM的同学一个思路，诸如分页加载这些事，以及Action的使用都需要自己具有RxSwift的功底，这里不对RxSwift的使用作出解答，可以到RxSwift以及Action对应处进行问询。

**Comment by ETmanwenhan** [comment]
谢谢！Action感觉自己不太熟悉。我还是自己手动创建监听好了。
